name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    uses: ./.github/workflows/e2e.yaml
    with:
      e2e-ref: ${{ github.ref }}
      e2e-repository: ${{ github.repository }}
